COMMENT ON TABLE "t_user" IS '로그인 계정과 회원 기본정보';
COMMENT ON COLUMN "t_user"."id" IS '회원 식별자';
COMMENT ON COLUMN "t_user"."provider" IS '가입 제공자: local, google 등';
COMMENT ON COLUMN "t_user"."provider_user_id" IS '외부 로그인 제공자의 회원 식별자';
COMMENT ON COLUMN "t_user"."email" IS '회원 이메일';
COMMENT ON COLUMN "t_user"."profile_image_url" IS '프로필 이미지 URL';
COMMENT ON COLUMN "t_user"."status" IS '계정 상태: active(사용), inactive(비활성)';
COMMENT ON COLUMN "t_user"."last_login_at" IS '마지막 로그인 시각';
COMMENT ON COLUMN "t_user"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_user"."updated_at" IS '수정 시각';
COMMENT ON COLUMN "t_user"."username" IS '로그인 아이디';
COMMENT ON COLUMN "t_user"."password" IS '해시 처리된 비밀번호';
COMMENT ON COLUMN "t_user"."real_name" IS '암호화된 회원 실명';
COMMENT ON COLUMN "t_user"."phone" IS '암호화된 회원 연락처';

COMMENT ON TABLE "t_user_roles" IS '회원별 권한';
COMMENT ON COLUMN "t_user_roles"."id" IS '회원 권한 식별자';
COMMENT ON COLUMN "t_user_roles"."user_id" IS '권한을 가진 회원 식별자';
COMMENT ON COLUMN "t_user_roles"."role_name" IS '권한: user(일반회원), staff(직원), admin(관리자)';
COMMENT ON COLUMN "t_user_roles"."created_at" IS '권한 부여 시각';

COMMENT ON TABLE "t_courses" IS '학원 교육 과정 기본정보';
COMMENT ON COLUMN "t_courses"."id" IS '과정 식별자';
COMMENT ON COLUMN "t_courses"."course_name" IS '과정명';
COMMENT ON COLUMN "t_courses"."summary" IS '과정 요약';
COMMENT ON COLUMN "t_courses"."description" IS '과정 상세 설명';
COMMENT ON COLUMN "t_courses"."thumbnail_file_id" IS '과정 대표 이미지 파일 식별자';
COMMENT ON COLUMN "t_courses"."is_visible" IS '사용자 페이지 노출 여부';
COMMENT ON COLUMN "t_courses"."status" IS '과정 상태: 모집중, 운영중, 마감, deleted(삭제)';
COMMENT ON COLUMN "t_courses"."sort_order" IS '노출 정렬 순서: 작은 값 우선';
COMMENT ON COLUMN "t_courses"."created_by" IS '등록한 직원·관리자 회원 식별자';
COMMENT ON COLUMN "t_courses"."updated_by" IS '마지막 수정 직원·관리자 회원 식별자';
COMMENT ON COLUMN "t_courses"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_courses"."updated_at" IS '수정 시각';

COMMENT ON TABLE "t_course_sessions" IS '교육 과정별 모집·운영 회차';
COMMENT ON COLUMN "t_course_sessions"."id" IS '과정 회차 식별자';
COMMENT ON COLUMN "t_course_sessions"."course_id" IS '소속 과정 식별자';
COMMENT ON COLUMN "t_course_sessions"."session_name" IS '회차명 또는 기수명';
COMMENT ON COLUMN "t_course_sessions"."session_no" IS '회차 번호';
COMMENT ON COLUMN "t_course_sessions"."start_date" IS '교육 시작일';
COMMENT ON COLUMN "t_course_sessions"."end_date" IS '교육 종료일';
COMMENT ON COLUMN "t_course_sessions"."capacity" IS '모집 정원';
COMMENT ON COLUMN "t_course_sessions"."status" IS '회차 상태: 모집중, 운영중, 마감, deleted(삭제)';
COMMENT ON COLUMN "t_course_sessions"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_course_sessions"."updated_at" IS '수정 시각';
COMMENT ON COLUMN "t_course_sessions"."class_start_time" IS '일일 수업 시작 시각';
COMMENT ON COLUMN "t_course_sessions"."class_end_time" IS '일일 수업 종료 시각';

COMMENT ON TABLE "t_enrollments" IS '회원의 과정 회차 신청';
COMMENT ON COLUMN "t_enrollments"."id" IS '과정 신청 식별자';
COMMENT ON COLUMN "t_enrollments"."user_id" IS '신청 회원 식별자';
COMMENT ON COLUMN "t_enrollments"."course_id" IS '신청 과정 식별자';
COMMENT ON COLUMN "t_enrollments"."session_id" IS '신청 회차 식별자';
COMMENT ON COLUMN "t_enrollments"."memo" IS '직원·관리자 처리 메모';
COMMENT ON COLUMN "t_enrollments"."applied_at" IS '신청 시각';
COMMENT ON COLUMN "t_enrollments"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_enrollments"."updated_at" IS '수정 시각';
COMMENT ON COLUMN "t_enrollments"."status" IS '신청 상태: pending(승인대기), approved(승인), rejected(반려)';

COMMENT ON TABLE "t_notices" IS '학원 공지사항';
COMMENT ON COLUMN "t_notices"."id" IS '공지 식별자';
COMMENT ON COLUMN "t_notices"."title" IS '공지 제목';
COMMENT ON COLUMN "t_notices"."content" IS '공지 내용';
COMMENT ON COLUMN "t_notices"."author_id" IS '작성 회원 식별자';
COMMENT ON COLUMN "t_notices"."author_name" IS '작성 당시 표시용 작성자명';
COMMENT ON COLUMN "t_notices"."view_count" IS '조회 수';
COMMENT ON COLUMN "t_notices"."is_visible" IS '사용자 페이지 노출 여부';
COMMENT ON COLUMN "t_notices"."is_pinned" IS '목록 상단 고정 여부';
COMMENT ON COLUMN "t_notices"."status" IS '공지 상태: published(게시), deleted(삭제)';
COMMENT ON COLUMN "t_notices"."published_at" IS '게시 시각';
COMMENT ON COLUMN "t_notices"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_notices"."updated_at" IS '수정 시각';

COMMENT ON TABLE "t_inquiries" IS '로그인 회원이 작성한 문의 원문';
COMMENT ON COLUMN "t_inquiries"."id" IS '문의 식별자';
COMMENT ON COLUMN "t_inquiries"."user_id" IS '문의 작성 회원 식별자';
COMMENT ON COLUMN "t_inquiries"."title" IS '문의 제목';
COMMENT ON COLUMN "t_inquiries"."content" IS '문의 내용';
COMMENT ON COLUMN "t_inquiries"."created_at" IS '작성 시각';
COMMENT ON COLUMN "t_inquiries"."updated_at" IS '마지막 수정 또는 답글 작성 시각';

COMMENT ON TABLE "t_inquiry_replies" IS '문의에 작성된 사용자·직원 답글';
COMMENT ON COLUMN "t_inquiry_replies"."id" IS '문의 답글 식별자';
COMMENT ON COLUMN "t_inquiry_replies"."inquiry_id" IS '원문 문의 식별자';
COMMENT ON COLUMN "t_inquiry_replies"."user_id" IS '답글 작성 회원 식별자; 권한은 t_user_roles에서 확인';
COMMENT ON COLUMN "t_inquiry_replies"."content" IS '답글 내용';
COMMENT ON COLUMN "t_inquiry_replies"."created_at" IS '작성 시각';
COMMENT ON COLUMN "t_inquiry_replies"."updated_at" IS '수정 시각';

COMMENT ON TABLE "t_files" IS '업로드 파일 메타데이터';
COMMENT ON COLUMN "t_files"."id" IS '파일 식별자';
COMMENT ON COLUMN "t_files"."original_name" IS '업로드 당시 원본 파일명';
COMMENT ON COLUMN "t_files"."stored_name" IS '저장소에 저장된 파일명';
COMMENT ON COLUMN "t_files"."file_path" IS '로컬 저장 파일 경로';
COMMENT ON COLUMN "t_files"."mime_type" IS '파일 MIME 유형';
COMMENT ON COLUMN "t_files"."file_size" IS '파일 크기(byte)';
COMMENT ON COLUMN "t_files"."created_at" IS '업로드 시각';
COMMENT ON COLUMN "t_files"."storage_type" IS '저장소 유형: local(서버), cloudinary(Cloudinary)';
COMMENT ON COLUMN "t_files"."bucket" IS '외부 저장소 버킷 또는 Cloudinary 클라우드명';
COMMENT ON COLUMN "t_files"."storage_key" IS '저장소 내부 파일 키';
COMMENT ON COLUMN "t_files"."public_url" IS '외부 공개 URL';
COMMENT ON COLUMN "t_files"."updated_at" IS '수정 시각';
COMMENT ON COLUMN "t_files"."uploaded_by" IS '업로드한 회원 식별자';
COMMENT ON COLUMN "t_files"."status" IS '파일 상태: active(사용), deleted(삭제)';

COMMENT ON TABLE "t_file_links" IS '파일과 과정·공지·배너 등 업무 데이터의 연결';
COMMENT ON COLUMN "t_file_links"."id" IS '파일 연결 식별자';
COMMENT ON COLUMN "t_file_links"."file_id" IS '연결할 파일 식별자';
COMMENT ON COLUMN "t_file_links"."target_table" IS '연결 대상 테이블명: 예) t_courses, t_notices';
COMMENT ON COLUMN "t_file_links"."target_id" IS '연결 대상 데이터 식별자';
COMMENT ON COLUMN "t_file_links"."file_role" IS '파일 용도: attachment, description_image 등';
COMMENT ON COLUMN "t_file_links"."sort_order" IS '파일 표시 순서: 작은 값 우선';
COMMENT ON COLUMN "t_file_links"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_file_links"."updated_at" IS '수정 시각';

COMMENT ON TABLE "t_banner" IS '홈페이지 노출 배너';
COMMENT ON COLUMN "t_banner"."id" IS '배너 식별자';
COMMENT ON COLUMN "t_banner"."title" IS '배너 제목';
COMMENT ON COLUMN "t_banner"."subtitle" IS '배너 부제목';
COMMENT ON COLUMN "t_banner"."description" IS '배너 설명';
COMMENT ON COLUMN "t_banner"."image_file_id" IS '배너 이미지 파일 식별자';
COMMENT ON COLUMN "t_banner"."link_url" IS '배너 클릭 이동 URL';
COMMENT ON COLUMN "t_banner"."link_target" IS '링크 열기 방식: _self 또는 _blank';
COMMENT ON COLUMN "t_banner"."position" IS '배너 노출 위치: 기본값 main';
COMMENT ON COLUMN "t_banner"."is_visible" IS '노출 여부';
COMMENT ON COLUMN "t_banner"."status" IS '배너 상태: active(사용), deleted(삭제)';
COMMENT ON COLUMN "t_banner"."sort_order" IS '노출 순서: 작은 값 우선';
COMMENT ON COLUMN "t_banner"."start_at" IS '노출 시작 시각';
COMMENT ON COLUMN "t_banner"."end_at" IS '노출 종료 시각';
COMMENT ON COLUMN "t_banner"."created_by" IS '등록한 직원·관리자 회원 식별자';
COMMENT ON COLUMN "t_banner"."updated_by" IS '마지막 수정 직원·관리자 회원 식별자';
COMMENT ON COLUMN "t_banner"."created_at" IS '생성 시각';
COMMENT ON COLUMN "t_banner"."updated_at" IS '수정 시각';

COMMENT ON TABLE "t_test1" IS '개발용 테스트 부모 테이블';
COMMENT ON COLUMN "t_test1"."id" IS '테스트 데이터 식별자';
COMMENT ON COLUMN "t_test1"."title" IS '테스트 제목';
COMMENT ON COLUMN "t_test1"."content" IS '테스트 내용';
COMMENT ON COLUMN "t_test1"."created_dt" IS '생성 시각';

COMMENT ON TABLE "t_test1_child" IS '개발용 테스트 자식 테이블';
COMMENT ON COLUMN "t_test1_child"."id" IS '테스트 자식 데이터 식별자';
COMMENT ON COLUMN "t_test1_child"."comment" IS '테스트 댓글 내용';
COMMENT ON COLUMN "t_test1_child"."created_dt" IS '생성 시각';
COMMENT ON COLUMN "t_test1_child"."test1_id" IS '부모 테스트 데이터 식별자';
